AWSTemplateFormatVersion: "2010-09-09"
Description: This CloudFormation template creates a new SageMaker UserProfile with a specific IAM role on an existing SageMaker Studio Domain to use Amazon SageMaker Canvas.

Parameters:
  UserProfileName:
    Type: String
    Description: The name of the new UserProfile
    Default: canvas-user

Resources:
  NewUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties:
      DomainId: !ImportValue SageMakerDomainId
      UserProfileName: !Ref UserProfileName
      UserSettings:
        ExecutionRole: !ImportValue SageMakerExecutionRoleName